### ISSUE TITLE
Describe offer filtering by language

### ISSUE THREAD

**Issue by mdonke** [AdobeDocs/journey-optimizer.en#1]
Issue in ./help/using/offers/api-reference/decisions-api/deliver-offers.md

Please describe how the offer language can be leveraged by the delivery API.

With "offer language" I'm referring to this section in [Create personalized offers](https://experienceleague.adobe.com/docs/journey-optimizer/using/offer-decisioniong/managing-offers-in-the-offer-library/creating-personalized-offers.html?lang=en) :

>Finally, select the language of your choice to help identify and manage what to display to the users.

**Comment by Alicesnk** [comment]
DOCAC-7188
