### ISSUE TITLE
Link "Limitations" is incorrect

### ISSUE THREAD

**Issue by Lexieyw** [AdobeDocs/journey-optimizer.en#10]
Issue in ./help/using/building-journeys/copy-to-sandbox.md

The link "Refer to Limitations" is incorrect. The pointed link didn't state any limitation. 
<img width="569" alt="Limitation" src="https://user-images.githubusercontent.com/103093510/176569573-d71873f5-8367-4532-a3e3-f538fa087143.PNG">

**Comment by Alicesnk** [comment]
Resolved
