### ISSUE TITLE
Hooks name is not matching the actual description of the hook

### ISSUE THREAD

**Issue by pjananth22123** [AdobeDocs/journey-optimizer.en#11]
Issue in ./help/using/landing-pages/lp-custom-js.md

The hook name for the "Custom hook to be called on failed form submission." seemed to be repetitive of the previous name. Please check.

![image](https://user-images.githubusercontent.com/7193479/180610680-2693b564-90c9-4bfa-acc7-190c01896f7a.png)

**Comment by juliette-massardier** [comment]
Thanks for spotting this. It will be fixed soon!
