### ISSUE TITLE
First/Last n in Array - Returned values are backwards

### ISSUE THREAD

**Issue by Danny-Donuts** [AdobeDocs/journey-optimizer.en#15]
Issue in ./help/using/personalization/functions/arrays-list.md

### First n in array
sorted in ascending order
Current: returns the top five orders with the **highest** price

Due to Ascending order it should be:
returns the **first** five orders with the **lowest** price

### Last n in array
sorted in ascending order
Current: returns the top five orders with the **lowest** price

Due to Ascending order it should be:
returns the **last** five orders with the **highest** price

**Comment by Alicesnk** [comment]
Resolved
