### ISSUE TITLE
"Journey Optimizer comes wit built-in message capabilities."

### ISSUE THREAD

**Issue by lesutton** [AdobeDocs/journey-optimizer.en#16]
https://experienceleague.adobe.com/docs/journey-optimizer/using/orchestrate-journeys/about-journey-building/journeys-message.html?lang=en

"Journey Optimizer comes wit built-in message capabilities."

replace with:

"Journey Optimizer comes with built-in message capabilities."

**Comment by Alicesnk** [comment]
resolved
