### ISSUE TITLE
Reference IDs in sample calls contain slang references :)

### ISSUE THREAD

**Issue by mdaniel12** [AdobeDocs/journey-optimizer.en#17]
Issue in ./help/using/offers/api-reference/offer-delivery-api/decisioning-api.md

Hi team,

My customer raised that in the example decision IDs the following string can be found and they deemed this as unprofessional. "1337-c0de-c0fefec0fefe"

Link to page: https://experienceleague.adobe.com/docs/journey-optimizer/using/offer-decisioning/api-reference/offer-delivery-api/decisioning-api.html?lang=en

Regards,
Mark

**Comment by Alicesnk** [comment]
DOCAC-8088

**Comment by Alicesnk** [comment]
Thanks for your feedback @mdaniel12. This is now resolved.
