### ISSUE TITLE
Table title misleading

### ISSUE THREAD

**Issue by angeli-adobe** [AdobeDocs/journey-optimizer.en#18]
Issue in ./help/using/reports/global-report.md

The table "Email and SMS metrics" contains also dimensions. So the title is misleading. Possible solution:
- add "dimensions" in the title > easy
- split metrics and dimensions in different table > better in terms of user experience.

**Comment by Alicesnk** [comment]
DOCAC-8087

**Comment by Alicesnk** [comment]
Thanks for your feedback @angeli-adobe. This is now resolved.
