### ISSUE TITLE
Subject of the event?

### ISSUE THREAD

**Issue by dwright-adobe** [AdobeDocs/journey-optimizer.en#22]
Issue in ./help/using/event/experience-event-schema.md

"Declare an identity field for identifying the subject of the event."

Can you clarify what is meant by the "subject" of the event? Is this and identity for the customer?

**Comment by Alicesnk** [comment]
DOCAC-8085

**Comment by Alicesnk** [comment]
Thanks for your feedback @dwright-adobe. This is now resolved.
