### ISSUE TITLE
Wrong links to math functions

### ISSUE THREAD

**Issue by barnato-v** [AdobeDocs/journey-optimizer.en#23]
Issue in ./help/using/personalization/functions/functions.md

Hi I think the math functions this page have the wrong links.

*  Absolute: https://experienceleague.adobe.com/docs/journey-optimizer/using/personalized-dynamic-content/personalization/build-expressions/functions/objects.html?lang=en#absolute
* Random: https://experienceleague.adobe.com/docs/journey-optimizer/using/personalized-dynamic-content/personalization/build-expressions/functions/objects.html?lang=en#random
* Round down: https://experienceleague.adobe.com/docs/journey-optimizer/using/personalized-dynamic-content/personalization/build-expressions/functions/objects.html?lang=en#round-down
* Round up: https://experienceleague.adobe.com/docs/journey-optimizer/using/personalized-dynamic-content/personalization/build-expressions/functions/objects.html?lang=en#round-up
* To percentage: https://experienceleague.adobe.com/docs/journey-optimizer/using/personalized-dynamic-content/personalization/build-expressions/functions/objects.html?lang=en#to-percentage
* To precision: https://experienceleague.adobe.com/docs/journey-optimizer/using/personalized-dynamic-content/personalization/build-expressions/functions/objects.html?lang=en#to-precision

They should be pointing to the following math.md file which for some reason is no longer listed on the TOC https://github.com/AdobeDocs/journey-optimizer.en/blob/63e250919cac5f7a3c010805d3333d204a6f99dc/help/using/personalization/functions/math.md

* Absolute: https://github.com/AdobeDocs/journey-optimizer.en/blob/63e250919cac5f7a3c010805d3333d204a6f99dc/help/using/personalization/functions/math.md#absolute-absolute
* Random: https://github.com/AdobeDocs/journey-optimizer.en/blob/63e250919cac5f7a3c010805d3333d204a6f99dc/help/using/personalization/functions/math.md#random-random
* Round down: https://github.com/AdobeDocs/journey-optimizer.en/blob/63e250919cac5f7a3c010805d3333d204a6f99dc/help/using/personalization/functions/math.md#round-down-round-down
* Round up: https://github.com/AdobeDocs/journey-optimizer.en/blob/63e250919cac5f7a3c010805d3333d204a6f99dc/help/using/personalization/functions/math.md#round-up-round-up 
* To percentage: https://github.com/AdobeDocs/journey-optimizer.en/blob/63e250919cac5f7a3c010805d3333d204a6f99dc/help/using/personalization/functions/math.md#to-percentage-to-percentage 
* To precision https://github.com/AdobeDocs/journey-optimizer.en/blob/63e250919cac5f7a3c010805d3333d204a6f99dc/help/using/personalization/functions/math.md#to-precision-to-precision

**Comment by Alicesnk** [comment]
DOCAC-8084
