### ISSUE TITLE
Incorrect 'Create First Journey' Link

### ISSUE THREAD

**Issue by jtwood426** [AdobeDocs/journey-optimizer.en#24]
Issue in ./help/ajo-home.md

The "Create Your First Journey" link appears to point to the wrong content. It points to the [multi-channel use case document](https://experienceleague.adobe.com/docs/journey-optimizer/using/orchestrate-journeys/journey-use-cases/business-use-cases/journeys-uc.html) instead of the [first journey document](https://experienceleague.adobe.com/docs/journey-optimizer/using/orchestrate-journeys/create-journey/journey-gs.html).

**Comment by Alicesnk** [comment]
Thanks for your feedback. This is now resolved.
