### ISSUE TITLE
Learn More Jump Links Do Not Point to Existing Anchor

### ISSUE THREAD

**Issue by jtwood426** [AdobeDocs/journey-optimizer.en#27]
Issue in ./help/using/email/fragments.md

Under "Create Fragments", two "learn more" jump links point to an anchor that does not exist

1. https://experienceleague.adobe.com/docs/journey-optimizer/using/email/fragments.html?lang=en#create-template-from-scratch
2. https://experienceleague.adobe.com/docs/journey-optimizer/using/email/fragments.html?lang=en#save-as-template

**Comment by Alicesnk** [comment]
Thanks for raising this issue @jtwood426 . We'll update shortly
Internal reference > DOCAC-8883

**Comment by juliette-massardier** [comment]
Page has been completely updated with new sections so it fixed the issue.
