### ISSUE TITLE
Run on sentence and confusing read.

### ISSUE THREAD

**Issue by Mattycsgithub** [AdobeDocs/journey-optimizer.en#28]
Issue in ./help/using/building-journeys/journey.md

The omnichannel journey designer helps you build multi-step journeys with targeted audiences, updates based on real-time customer or business interactions, and omnichannel messages using an intuitive drag-and-drop interface.

The omnichannel journey designer assists you in constructing multi-step journeys, specifically targeting audiences, and incorporating updates based on real-time customer or business interactions. It also enables you to create omnichannel messages through an intuitive drag-and-drop interface.

**Comment by Alicesnk** [comment]
Thanks for your feedback. The changes you suggested have been implemented.
