### ISSUE TITLE
Run-on sentences and confusing read.

### ISSUE THREAD

**Issue by Mattycsgithub** [AdobeDocs/journey-optimizer.en#29]
Issue in ./help/using/building-journeys/journey-gs.md

When editing an action or condition activity, you can define an alternative path in case of error or timeout. If the processing of the activity interrogating a third-party system exceeds the timeout duration defined in the journey’s properties (Timeout and error field), the second path will be chosen to perform a potential fallback action.

When editing an action or condition activity, you have the option to specify an alternative path in the event of an error or timeout. If the processing of the activity, which involves querying a third-party system, surpasses the duration specified in the journey's properties for timeout and error handling, the second path will be selected to execute a fallback action if necessary.

**Comment by Alicesnk** [comment]
Resolved, thanks for your feedback
