### ISSUE TITLE
They not he

### ISSUE THREAD

**Issue by Mattycsgithub** [AdobeDocs/journey-optimizer.en#31]
Issue in ./help/using/building-journeys/entry-management.md

For recurring journeys: the profile enters the journey on each recurrence, if he is in the segment/expected status. If he was still in the journey from a previous recurrence, he will restart it from the beginning.

In business event journeys starting with a Read segment activity: knowing that this journey is based on the reception of a business event, if the profile is qualified in the expected segment, he will enter the journey for each business event received, meaning that this profile can be multiple times in the same journey, at the same time, but in the context of different business events.

For recurring journeys: the profile enters the journey on each recurrence, if they are in the segment/ expected status. If they were still in the journey from a previous recurrence, they will restart it from the beginning.

In business event journeys starting with a Read segment activity: knowing that this journey is based on the reception of a business event, if the profile is qualified in the expected segment, they will enter the journey for each business event received, meaning that this profile can be multiple times in the same journey, at the same time, but in the context of different business events.

**Comment by Alicesnk** [comment]
Thanks for your feedback. Updates have been implemented.
