### ISSUE TITLE
No possessive apostrophe or plural adjective

### ISSUE THREAD

**Issue by Mattycsgithub** [AdobeDocs/journey-optimizer.en#32]
Issue in ./help/using/building-journeys/reaction-events.md

Content:
Email clients such as Gmail allow image blocking. Emails opens are tracked using a 0-pixel image included in the email. If images are blocked, email opens will not be taken into account.

Suggested edit:
Email clients such as Gmail allow image blocking. Email opens are tracked using a 0-pixel image included in the email. If images are blocked, email opens will not be taken into account.

**Comment by Alicesnk** [comment]
Resolved, thanks
