### ISSUE TITLE
Two options not three

### ISSUE THREAD

**Issue by Mattycsgithub** [AdobeDocs/journey-optimizer.en#33]
Issue in ./help/using/building-journeys/wait-activity.md

If you want to wait before executing the next activity in the path, you can use a Wait activity. It allows you to define the moment when the next activity will be executed. Three options are available:

[Duration](https://experienceleague.adobe.com/docs/journey-optimizer/using/orchestrate-journeys/about-journey-building/wait-activity.html?lang=en#duration)
[Custom](https://experienceleague.adobe.com/docs/journey-optimizer/using/orchestrate-journeys/about-journey-building/wait-activity.html?lang=en#custom)

Suggested edit:
If you want to wait before executing the next activity in the path, you can use a Wait activity. It allows you to define the moment when the next activity will be executed. Two options are available:

[Duration](https://experienceleague.adobe.com/docs/journey-optimizer/using/orchestrate-journeys/about-journey-building/wait-activity.html?lang=en#duration)
[Custom](https://experienceleague.adobe.com/docs/journey-optimizer/using/orchestrate-journeys/about-journey-building/wait-activity.html?lang=en#custom)

**Comment by Alicesnk** [comment]
Thanks for your feedback.
