### ISSUE TITLE
Run-on sentencce

### ISSUE THREAD

**Issue by Mattycsgithub** [AdobeDocs/journey-optimizer.en#34]
Issue in ./help/using/building-journeys/read-segment.md

To do this, click the Edit journey schedule link to access the journey’s properties, then configure the Scheduler type field.

Suggested edit:

To do this, click the Edit journey schedule link to access the journey’s properties.  Then, configure the Scheduler type field.

**Comment by Alicesnk** [comment]
Updated, thanks
