### ISSUE TITLE
Adjective not noun, too many prepositional commas, preposition way too long and just confusing to read

### ISSUE THREAD

**Issue by Mattycsgithub** [AdobeDocs/journey-optimizer.en#35]
Issue in ./help/using/building-journeys/read-segment.md

Force reentrance on recurrence: this option allows you to make all profiles still present in the journey automatically exit it on the next execution. For example, if you have a 2 days wait in a daily recurrent journey, by activating this option, profiles will always be moved on the next journey execution (so the day after), whether they are in the next run audience or not. If the lifespan of your profiles in this journey may be longer than the recurrence frequency, do not activate this option to make sure that profiles can finish their journey.

Suggested edit:

Enabling the "Force Reentrance on Recurrence" option allows you to automatically remove all profiles that are currently in the journey during the next execution. For instance, if there is a 2-day wait in a daily recurring journey, activating this option will consistently move profiles to the subsequent journey execution (the following day), regardless of whether they are part of the next run audience. However, if the duration of profiles in this journey can exceed the recurrence frequency, it is advisable not to enable this option to ensure that profiles can complete their journey.

**Comment by Alicesnk** [comment]
Thanks for your feedback. This section has been updated
