### ISSUE TITLE
Failure to indicate technical term or option by use of apostrophes or bold

### ISSUE THREAD

**Issue by Mattycsgithub** [AdobeDocs/journey-optimizer.en#36]
Issue in ./help/using/building-journeys/read-segment.md

One-shot Read segment journeys move to the Finished status 30 days after the journey execution. For scheduled Read segments, it is 30 days after the execution of the last occurrence.

Suggested edit:
One-shot "Read segment" journeys move to the "Finished" status 30 days after the journey execution. For scheduled "Read segments", it is 30 days after the execution of the last occurrence.

**Comment by Alicesnk** [comment]
Done, thanks!
