### ISSUE TITLE
"Tested" not "test" and run-on sentence

### ISSUE THREAD

**Issue by Mattycsgithub** [AdobeDocs/journey-optimizer.en#37]
Issue in ./help/using/building-journeys/read-segment.md

The Read Segment activity allows you to test the journey either on a unitary profile, or on 100 randomly test profiles selected among the profiles qualified for the segment.

To do this, activate the test mode, then select the desired option from the left pane.

Suggested edit:
The Read Segment activity allows you to test the journey either on a unitary profile, or on 100 randomly tested profiles selected among the profiles qualified for the segment.

To do this, activate the test mode. Then, select the desired option from the left pane.

**Comment by Alicesnk** [comment]
Thanks for your feedback. The sentence has been improved, changes are now live.
