### ISSUE TITLE
Confusing read improper grammar. 

### ISSUE THREAD

**Issue by Mattycsgithub** [AdobeDocs/journey-optimizer.en#38]
Issue in ./help/using/building-journeys/using-adobe-campaign-standard.md

For email, if you’re using a profiles transactional template, the unsubscription mechanism is handled built-in by Campaign Standard. You simply add an Unsubscription link content block in the template ([learn more](https://experienceleague.adobe.com/docs/campaign-standard/using/communication-channels/transactional-messaging/getting-started-with-transactional-msg.html?lang=en)). If you’re using an event-based template (rtEvent), you need to add, in the message, a link passing the person’s email in the URL parameter and pointing to an unsubscription landing page. You need to create this landing page and make sure the person’s decision to unsubscribe is transmitted to Adobe.

Suggested edit:

When utilizing a profile's transactional template for email, the unsubscription mechanism is automatically handled by Campaign Standard. To implement this, you can easily include an Unsubscription link content block within the template (learn more). However, if you're using an event-based template (rtEvent), you must incorporate a link in the message that passes the recipient's email as a URL parameter and directs them to an unsubscription landing page. It is necessary to create this landing page and ensure that the recipient's decision to unsubscribe is effectively transmitted to Adobe.

**Comment by Alicesnk** [comment]
Thanks for your feedback and the nice rewording! This note has been updated.
