### ISSUE TITLE
Architecture diagram needs a box for first party data

### ISSUE THREAD

**Issue by abhardwaj-dev** [AdobeDocs/journey-optimizer.en#40]
Issue in ./help/using/start/get-started.md

In the architecture diagram (help/using/start/assets/ajo-architecture.png) there is no box indicating that first party client owned data can be brought into the Platform (AEP). We need to add this since most of the data currently being ingested into AEP is batch first party data.

**Comment by Alicesnk** [comment]
Thanks for your feedback. The page will soon be updated.
Internal reference > DOCAC-9002
