### ISSUE TITLE
Missing closing parentheses 

### ISSUE THREAD

**Issue by abhardwaj-dev** [AdobeDocs/journey-optimizer.en#41]
Issue in ./help/using/building-journeys/expression/expressionadvanced.md

In the paragraph below "Need for parameters when building conditions with the advanced expression editor", the closing parentheses is missing. The opening parentheses is present before "see". It feels like the paragraph is not structured correctly and should read as follows:
If you select a field from an external data source requiring a parameter to be called (For example, in a weather-related data source, a frequently used parameter will be “city”. See this page for more info), you must select where you want to get this city parameter. Functions can also be applied to parameters to perform format changes or concatenations.

**Comment by Alicesnk** [comment]
Thanks for your feedback. The page will soon be updated.
Internal reference > DOCAC-9001

**Comment by FlorentVAdobe** [comment]
part of the paragraph was accidentally deleted. I reversed to the paragraph with the right content:

If you select a field from an external data source requiring a parameter to be called (see [this page](../../datasource/external-data-sources.md)), a new tab appears on the right to let you specify this parameter. The parameter value can come from the events positioned in the journey or the Experience Platform data source (and not from other external data sources). For example, in a weather-related data source, a frequently used parameter will be "city". As a result, you must select where you want to get this city parameter. Functions can also be applied to parameters to perform format changes or concatenations.
