### ISSUE TITLE
Word usage appears incorrect

### ISSUE THREAD

**Issue by abhardwaj-dev** [AdobeDocs/journey-optimizer.en#42]
Issue in ./help/using/offers/offer-activities/create-offer-activities.md

Does the work "ranged" in the paragraph below supposed to be "ranked"?

If the two collections are evaluated at the same time, as there are two eligible offers from evaluation criteria A and three eligible offers from evaluation criteria B, the five offers will all be stack **ranged** together based on the value determined by the respective ranking methods. Two offers are requested, therefore the top two eligible offers from these five offers will be returned.

**Comment by Alicesnk** [comment]
Thanks for your feedback. The page will soon be updated.
Internal reference > DOCAC-9000

**Comment by Alicesnk** [comment]
Resolved
