### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by abhardwaj-dev** [AdobeDocs/journey-optimizer.en#43]
Issue in ./help/using/offers/data-collection/create-dataset.md

The link at the end of this sentence is broken and doesn't take the user to a page detailing ranking strategy.

"This dataset can now be selected to collect event data when [creating a ranking strategy](https://experienceleague.adobe.com/docs/journey-optimizer/using/offer-decisioning/collect-event-data/create-dataset.html?lang=en#create-ranking-strategy)."

**Comment by Alicesnk** [comment]
Thanks for your feedback. The page will soon be updated.
Internal reference > DOCAC-8999

**Comment by Alicesnk** [comment]
The issue is now resolved
