### ISSUE TITLE
Incomplete sentence

### ISSUE THREAD

**Issue by abhardwaj-dev** [AdobeDocs/journey-optimizer.en#44]
Issue in ./help/using/offers/api-reference/offers-api/placements/placements-list.md

In the table located in the Paging section with various parameters, the Description cell for the "q" Parameter appears to have an incomplete sentence at the end where it says "The characters `+ - = &&"

**Comment by Alicesnk** [comment]
Thanks for your feedback. The page will soon be updated.
Internal reference > DOCAC-8998

**Comment by Alicesnk** [comment]
The issue is now resolved
