### ISSUE TITLE
Broken link for Detailed documentation on Content templates APIs

### ISSUE THREAD

**Issue by himanshu-pathak** [AdobeDocs/journey-optimizer.en#45]
Issue in ./help/using/rn/release-notes.md

https://experienceleague.adobe.com/docs/journey-optimizer/using/whats-new/release-notes.html?lang=en

July release notes -> New Capabilities -> Content templates APIs. 
The link to detailed documentation points to https://developer.adobe.com/journey-optimizer-apis/references/content-templates/ which gives a 404. 

In addition I'd highly recommend that we have a dedicated page for each release like AEM does for its service packs. that way the hyperlinks are more reliable. the current release can always redirect to the latest month release page. 

https://experienceleague.adobe.com/docs/experience-manager-65/release-notes/release-notes.html?lang=en

**Comment by Alicesnk** [comment]
the issue is now resolved, thanks
