### ISSUE TITLE
Time zone for offer start and end dates should be stated

### ISSUE THREAD

**Issue by abhardwaj-dev** [AdobeDocs/journey-optimizer.en#46]
Issue in ./help/using/offers/offer-library/creating-personalized-offers.md

In Step 2 "Specify the offer’s name as well as its start and end date and time. Outside of these dates, the offer won’t be selected by the Decisioning engine." we should specify which time zone is used for the start and end dates - UTC, user's time zone, sandbox time zone, US Eastern Time etc.

**Comment by Alicesnk** [comment]
Thanks for your feedback @abhardwaj-dev. We'll check and update shortly.
Internal Ref > DOCAC-9540

**Comment by juliette-massardier** [comment]
Sorry I missed that one. I asked the PMs to confirm before I update the documentation.

**Comment by Alicesnk** [comment]
Got confirmation from the team that the time selected is in the client time zone & is converted to backend as UTC time. So for example, I am here in Mountain Time MT and set start time as 3pm. The backend will convert the start time to UTC which would be +6 hours so 9pm UTC

Added this note: "When selecting times, your current time zone is taken into account." to this section: https://experienceleague.adobe.com/en/docs/journey-optimizer/using/offer-decisioning/managing-offers-in-the-offer-library/configure-offers/creating-personalized-offers#create-offer
