### ISSUE TITLE
Page not found error

### ISSUE THREAD

**Issue by thefiratyildirim** [AdobeDocs/journey-optimizer.en#47]
Issue in https://experienceleague.adobe.com/docs/journey-optimizer/using/personalization/personalize.html?lang=en
![adobe page error](https://github.com/AdobeDocs/journey-optimizer.en/assets/39015039/f3c3aa70-cb2f-47f6-bf4c-974ebc230c15)

**Comment by thefiratyildirim** [comment]
When I checked the documentation, I was trying to go to Personalization page however when I clicked the link it does not work. There is a broken link and maybe you need to remove it or fix it.

**Comment by Alicesnk** [comment]
Thanks for your feedback @thefiratyildirim. We'll add a redirect to avoid this.
Internal Ref > DOCAC-9541

**Comment by Alicesnk** [comment]
The issue is now resolved.
