### ISSUE TITLE
Missing step in Audience Building

### ISSUE THREAD

**Issue by jmays-tech** [AdobeDocs/journey-optimizer.en#48]
On the "Build segment definitions" page the step where you choose either "compose audience" or "build rule" is missing. It should appear before the segment definition screen and the user needs to select "build rule" to see the step 2 screen.

 https://experienceleague.adobe.com/docs/journey-optimizer/using/audiences-profiles-identities/audiences/creating-a-segment-definition.html?lang=en#video-segment

**Comment by Alicesnk** [comment]
Thanks for your feedback @jmays-tech. We'll check and update shortly.
Internal ref > DOCAC-9539

**Comment by Alicesnk** [comment]
The issue has been resolved.
