### ISSUE TITLE
Audience composition and external audiences reported as beta while as GA from the wiki

### ISSUE THREAD

**Issue by decaroa** [AdobeDocs/journey-optimizer.en#49]
Good day team.
[This page](https://experienceleague.adobe.com/docs/journey-optimizer/using/audiences-profiles-identities/audiences/about-audiences.html?lang=en) is currently reporting:
"In addition, you can also target Adobe Experience Platform audiences created using [audience compositions](https://experienceleague.adobe.com/docs/journey-optimizer/using/audiences-profiles-identities/audiences/audience-orchestration/get-started-audience-orchestration.html?lang=en) or [uploaded from a CSV file](https://experienceleague.adobe.com/docs/experience-platform/segmentation/ui/overview.html?lang=en#import-audience). These capabilities are currently available as a private beta."

While the [AJO beta's programs](https://wiki.corp.adobe.com/display/CJM/AJO+Betas) in the Adobe's wiki is reporting:
"Audience Portal / Composition - GA 23.7".

Could you please confirm in the public documentation if those features are GA or not?

Thanks,
Alberto

Issue in ./help/using/audience/about-audiences.md

**Comment by Alicesnk** [comment]
Thanks for your feedback @decaroa - the documentation has been updated since.
