### ISSUE TITLE
Example is not correct

### ISSUE THREAD

**Issue by abhardwaj-dev** [AdobeDocs/journey-optimizer.en#51]
Issue in ./help/using/personalization/functions/helpers.md

The example states "The following example lets all sums of product totals with the transaction in USD where the sum is greater than $100 and less than $1000." but the example just shows the syntax without showing how to use the helper function for this example.

**Comment by Alicesnk** [comment]
Thanks for your feedback @abhardwaj-dev, we'll update shortly.
Internal ref: DOCAC-10018
