### ISSUE TITLE
Dataset name for message feedback is incorrect

### ISSUE THREAD

**Issue by abhardwaj-dev** [AdobeDocs/journey-optimizer.en#53]
Issue in ./help/using/data/datasets-query-examples.md

The sample query shows the dataset name as cjm_message_feedback_event_dataset but the dataset name is actually ajo_message_feedback_event_dataset . It was probably changed at some point after the documentation was created.

**Comment by Alicesnk** [comment]
Internal ref > DOCAC-10179

**Comment by Alicesnk** [comment]
This has been resolved. Thanks for your feedback @abhardwaj-dev
