### ISSUE TITLE
Additional Adjustments to Update Profile Action.

### ISSUE THREAD

**Issue by dhwoolsey** [AdobeDocs/journey-optimizer.en#54]
Issue in ./help/using/building-journeys/update-profiles.md

We've run into a few customer issues where additional clarity in this doc could have prevented some issues. Here are the recommended updates:

1. Create a new section under the "Recommendations" section called "Dataset Selection"
2. Remove the last bullet from the "Recommendations" section and add the below text to the new "Dataset Selection" section (it's an updated version of the bullet we are asking to be removed):

"The Update Profile action will need a dataset with which to store the updates. Because the Update Profile action only updates the Profile store (and not Datalake), all Update Profile actions should be stored in a profile-enabled dataset dedicated to only Update Profile actions. Using a dataset that is also used for batch or streaming ingestion will result in newly onboarded data overwriting the changes made by the Update Profile action.

Additionally, the Update Profile activity configuration does not require an identity namespace. As such, ensure that the selected dataset uses the same Identity namespace that was used by the action that launched the journey as it is this namespace these updates will use. The identity map can also be used by the selected dataset. Failure to select a data set with the correct namespace or one that uses identity map will cause the Update Profile activity to fail." 

3. Lastly, change the "Recommendations" section header to read "Key Concepts." We actually don't recommend much of anything in that section. There are just Key Concepts the customers need to understand when using this AJO Action.

**Comment by Alicesnk** [comment]
Thanks for your feedback @dhwoolsey - we'll update accordingly 
Internal reference > DOCAC-10298

**Comment by Alicesnk** [comment]
This issue has been resolved
