### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by sreecharan81** [AdobeDocs/journey-optimizer.en#57]
Issue in ./help/using/building-journeys/general-events.md

https://experienceleague.adobe.com/en/docs/journey-optimizer/using/orchestrate-journeys/about-journey-building/general-events#:~:text=is%20reached.%20We-,recommand,-that%20you%20always

could change "recommand" to "recommend"

**Comment by Alicesnk** [comment]
thanks for your feedback @sreecharan81 - this has been updated
Internal reference > /DOCAC-10403
