### ISSUE TITLE
Document correction

### ISSUE THREAD

**Issue by sreecharan81** [AdobeDocs/journey-optimizer.en#58]
Issue in ./help/using/building-journeys/general-events.md

https://experienceleague.adobe.com/en/docs/journey-optimizer/using/orchestrate-journeys/about-journey-building/general-events#:~:text=one%20event%20is-,reveiced,-within%20the%20timeout

Could change "reveiced" to "received"

**Comment by Alicesnk** [comment]
thanks for your feedback @sreecharan81 - this has been updated
Internal reference > /DOCAC-10404
