### ISSUE TITLE
ODE datasets into profile

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/journey-optimizer.en#6]
Issue in ./help/using/offers/reports/get-started-events.md

For the following note
"Note that ODE DecisionEvents datasets are non-profile datasets, meaning that they cannot be ingested into Experience Platform for use by Real-time Customer Profile."

Are the ODE datasets Experience Event type?
Do they have a primary identity key in the events?
If so they can be ingested and related to profile so we may be able to change this note.

**Comment by Alicesnk** [comment]
DOCAC-8306

**Comment by juliette-massardier** [comment]
Hello, as per [DOCAC-8306](https://jira.corp.adobe.com/browse/DOCAC-8306), the ODE datasets are not Experience Event type as they have their own schema class: "Decision Event" and their schema has identityMap, so I assume the current note doesn't need to be changed.
