### ISSUE TITLE
Link missing for "Learn how to update your existing fragments in this section."

### ISSUE THREAD

**Issue by Lexie1919** [AdobeDocs/journey-optimizer.en#62]
Issue in ./help/using/rn/release-notes.md (https://experienceleague.adobe.com/en/docs/journey-optimizer/using/whats-new/release-notes)

There is no link for " Learn how to update your existing fragments in this section." in June release notes.

**Comment by Alicesnk** [comment]
hi @Lexie1919, thanks for your feedback. The section has been updated.
Internal reference: DOCAC-10673
