### ISSUE TITLE
Incorrect description for decisions permissions

### ISSUE THREAD

**Issue by thaissrguimaraes** [AdobeDocs/journey-optimizer.en#64]
Issue in ./help/using/administration/high-low-permissions.md

Under the manage decisions and view decisions permissions, it says "dataset.delete" is included, but that is incorrect. If I give myself view decisions or manage decisions I am unable to edit, manage or delete datasets.

**Comment by Alicesnk** [comment]
Thanks for raising this @thaissrguimaraes 
We'll check and update shortly
Internal reference: DOCAC-11082

**Comment by manbeneat** [comment]
Documentation has been corrected
