### ISSUE TITLE
Typo on page: journey-optimizer/using/push/design-push

### ISSUE THREAD

**Issue by mercurygates** [AdobeDocs/journey-optimizer.en#65]
Issue in ./help/using/push/design-push.md

I believe there's a typo!
<img width="882" alt="Screenshot 2024-07-24 at 13 49 04" src="https://github.com/user-attachments/assets/ddc6b037-5d21-47b8-8858-3b240af42a71">

**Comment by Alicesnk** [comment]
Thanks for spotting this @mercurygates - this typo has been fixed
internal reference > DOCAC-11081
