### ISSUE TITLE
Permissions must be opened within AJO

### ISSUE THREAD

**Issue by angeli-adobe** [AdobeDocs/journey-optimizer.en#71]
Issue in ./help/using/test-approve/approval-policies.md

In the first line of "Create approval policies" worth to specify the "Permissions" should be opened within AJO. If you open Permissions from Experience Platform, the tab for "Approval Policies" does not appears. 

Since the "Permissions" UI can opened from multiple points, I think it's better to add this specification.

**Comment by Alicesnk** [comment]
hi @angeli-adobe, thanks for your feedback. We'll update this section as suggested.
Internal reference > DOCAC-11222

**Comment by manbeneat** [comment]
Added specification to documentation => From the Administration menu **in Journey Optimizer,** access Permissions then Policies.
