### ISSUE TITLE
Markdown shown instead of HTML

### ISSUE THREAD

**Issue by pmonjo** [AdobeDocs/journey-optimizer.en#73]
Issue in ./help/using/personalization/create-conditions.md

There is a part of the page that has not correctly been converted from Markdown to HTML.

![image](https://github.com/user-attachments/assets/4dae97f4-4e3b-4f76-a43d-f8c513767d4d)

**Comment by Alicesnk** [comment]
hi @pmonjo, thanks for your feedback. We updated this section. Changes will be live later today.
Internal reference: DOCAC-11309
