### ISSUE TITLE
The video on this page appears to be no longer relevant

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/journey-optimizer.en#75]
Issue in ./help/using/administration/permissions-overview.md

Permissions are not managed in admin console as the video describes. They are managed in AEP permissions UI.

**Comment by Alicesnk** [comment]
hi @nhecht, thanks for creating this issue. We'll check and update as needed.
Internal reference > DOCAC-11368

**Comment by sanhaus** [comment]
The video has been hidden until it has been updated.
