### ISSUE TITLE
Small grammar error

### ISSUE THREAD

**Issue by purdueboiler1987** [AdobeDocs/journey-optimizer.en#76]
Issue in ./help/using/content-management/fragments.md

The second sentence should be "This functionality allows you to prebuild"

**Comment by Alicesnk** [comment]
hi @purdueboiler1987, thanks for creating this issue. We'll check and update as needed.
Internal reference > DOCAC-11388

**Comment by Alicesnk** [comment]
The issue has been resolved. Changes will be live later today.
