### ISSUE TITLE
Outdated content for user permissions

### ISSUE THREAD

**Issue by dwright-adobe** [AdobeDocs/journey-optimizer.en#77]
Issue in ./help/using/start/path/administrator.md

This paragraph is out-of-date:
"Set permissions for product profiles, including Sandboxes, and give access to your team members by assigning them to different product profiles. This step is performed in the [Admin Console](https://adminconsole.adobe.com/#_blank). Permissions are unitary rights that allow you to define the authorizations assigned to Product profile. Each permission is gathered under capabilities, e.g. Journey or Offers, which represents the different functionalities or objects in Journey Optimizer. Learn more in the [Permission levels](https://experienceleague.adobe.com/en/docs/journey-optimizer/using/access-control/privacy/high-low-permissions) section."
Granular user permissions such as sandbox permissions are no longer managed in Admin Console, but in the new Permissions screen in AJO/Platform.

**Comment by Alicesnk** [comment]
hi @dwright-adobe, thanks for your feedback.
We'll update shortly.
Internal reference > DOCAC-11466

**Comment by manbeneat** [comment]
Thanks for feedback! Documentation has been updated accordingly
