### ISSUE TITLE
Ranking of collections is unclear, the method to calculate results is not well explained.

### ISSUE THREAD

**Issue by ankurmehrotra** [AdobeDocs/journey-optimizer.en#8]
Issue in ./help/using/offers/offer-activities/create-offer-activities.md
![image](https://user-images.githubusercontent.com/15048072/171821341-dbae59ab-c745-4897-a65d-ed95f1734405.png)

Description: In Line Item 8 "You can also evaluate several criteria at the same time. To do so, drag and drop the collection on top of another."
It is not clear how this will work:

- Say two collections are together and they both make a profile elgibile for 2,3 offers respectively. If the request is for only 2 offers to be sent back (itemCount) then which ones will be selected? 
- In your example of ranking formula and scoring, how is the output determed for my above shared example?
- How is this going to work differently from collections in two different rows?
If we can consider these in documentation, it will explain vital differences to users.

**Comment by Alicesnk** [comment]
DOCAC-8089

**Comment by juliette-massardier** [comment]
Hi, thanks a lot for this comment, your request was relevant. I created a new subsection to clearly explain the difference.
DOCAC-8089 is resolved. Changes should be published tomorrow.

**Comment by juliette-massardier** [comment]
The new subsection is now live here: https://experienceleague.adobe.com/docs/journey-optimizer/using/offer-decisioning/create-manage-activities/create-offer-activities.html?#evaluation-criteria-order
Please let me know if it answers your needs. If so, you can close this issue. Thanks!
